const cells = {
  "range": "projects!A1:N135",
  "majorDimension": "ROWS",
  "values": [
    [
      "Project Name",
      "Place",
      "Authors",
      "Year",
      "Link",
      "Description ",
      "Does this project has to do with urban context? Y/N",
      "Is it a Citizen Science project?",
      "Nature topic",
      "Technology ",
      "Other Keywords",
      "Implementation",
      "student name",
      "Why is related/relevant to our ecology conversation / / why this inspre you?"
    ],
    [
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "explain better which are the categories of the project",
      "biodiversity, kingdom/species (taxonomy), five elements, conservation, pollution, waterscape, science dissemination/education",
      "AI, data, fabrication, digital fabrication, sensor, sampling, coding, biomedia",
      "",
      "speculative / prototype / complete"
    ],
    [
      "add NTFS cases"
    ],
    [
      "Popsicles of Pollution",
      "Taiwan",
      "Hung Yi-Chen, Guo Yi-hui and Cheng Yu-Ti",
      "2017",
      "https://www.theguardian.com/cities/gallery/2017/sep/01/popsicles-pollution-ice-lollies-taiwan-taipei-contaminated-waterways",
      "Students from New Taipei City collected samples from urban rivers, creeks and ports which they then froze in moulds and preserved in resin. ‘We hope when more people see this they can change their lifestyles'.",
      "Y",
      "N",
      "five elements, waterscape, food, pollution, material, waste",
      "fabrication",
      "",
      "complete"
    ],
    [
      " Instructables Insect Hotel",
      "",
      "",
      "",
      "https://www.instructables.com/id/Emergent-Insect-Hotels/?utm_source=newsletter&utm_medium=email",
      "",
      "Y",
      "N",
      "insect, biodiversity, conservation, animals, garden, habitat, bee, spider",
      "fabrication",
      "",
      "complete"
    ],
    [
      "Pure Imagination ",
      "Shanghai",
      "J Travis Russet",
      "2017",
      "http://archive.fabacademy.org/fabacademy2017/fablabshangai/students/190/final-project.html",
      "Fab Academy final project / (moss harvesting energy)",
      "N",
      "Y",
      "moss, utilization, resource, material, cell",
      "fabrication, digital fabrication, sensors, biomedia",
      "",
      "prototype"
    ],
    [
      "Faito ",
      "Madrid",
      "Pilar Caballero",
      "2018",
      "http://fab.academany.org/2018/labs/farmlabalgarve/students/pilar-caballero/FinalProject.html",
      "Fab Academy final project / (a diy kite that monitors air quality)",
      "N",
      "Y",
      "air, environment, pollution",
      "fabrication, digital fabrication, sensors",
      "",
      "prototype"
    ],
    [
      "Dirty Playground",
      "Rotterdam",
      "Manuel Steitz、Coltrane McDowell and Serina Tarkhanian",
      "2021",
      "https://www.designacademy.nl/p/about-dae/news/dae-team-wins-bio-design-challenge-prize",
      "annual Bio Design Challenge awarded project /It's about Rewilding and bringing ecological succession back in the city, connection\r\n between multi-generational people and soil ground & gamification labour\r\n connected to nature.",
      "Y",
      "N",
      "soil, ecosystem, rewild, symbiosis",
      "fabrication, biomedia",
      "",
      "prototype",
      "Deng Zhiwen"
    ],
    [
      "in love with the world",
      "tate modern",
      "anicka yi",
      "2021",
      "https://www.designboom.com/art/anicka-yi-tate-modern-hyundai-motor-london-floating-machines-aerobes-10-11-2021/",
      "an exhibition in tate modern / anicka yi transforms tate modern into a fragrant ecosystem of floating machines to\r\n propose a new type of industrial vision and speculates on the possibility of\r\n machines evolving into independent life forms. The machine can interact with\r\n environment & human beings as nature creatures.",
      "N",
      "N",
      "multi-species, air, more-than-human",
      "sensors, digital fabrication, fabrication",
      "mimicry",
      "speculative",
      "Deng Zhiwen"
    ],
    [
      "PAPILIO",
      "berlin",
      "tobias trübenabacher",
      "2021",
      "https://www.designboom.com/design/papilio-wind-powered-street-light-tobias-trubenabacher-05-17-2021/",
      "graduation project at the university of the arts in berlin",
      "Y",
      "N",
      "footprint, wind, light",
      "fabrication, sensors",
      "",
      "complete",
      "Deng Zhiwen",
      "physical wind phenomena in cities are enforcing the wind intensity in urban\n surroundings.This product can works with vertical (NATURAL wind) as well as\n horizontal air streams (e.g. airflow caused byTRAFFIC). A kind of urban\n nature."
    ],
    [
      "IKARUS",
      "berlin",
      "tobias trübenabacher",
      "2021",
      "http://tobiastruebenbacher.com/ux-portfolio/ikarus/",
      "Personal project",
      "N",
      "N",
      "light, bionic",
      "fabrication, digital fabrication",
      "",
      "complete",
      "Deng Zhiwen",
      "It's about light, from changing. It's variable and can be changed by individually\n programmed motors which are connected by different levers and joints. Which means it can react with or reflect some phenomena."
    ],
    [
      "circular artwork",
      "Ohio",
      "John Sabraw",
      "2019/2017",
      "https://www.johnsabraw.com/studio",
      "",
      "N",
      "N",
      "pollution, waterscape, pigment, color, landscape ",
      "fabrication, sampling",
      "paintings",
      "complete",
      "Zhu Zihan",
      "His works extracts paints from industrial-contaminated water.There is a terrible beauty in the resulting artworks that balance the delicate with the brutal.These paintings seek to express the sublimity of nature, but also the fragility of our relationship with it."
    ],
    [
      "inkware（nature pigment creator）",
      "Wellington, New Zealand",
      "Tahlia Conrad-Hinga",
      "2021",
      "https://www.behance.net/gallery/120247317/Inkware-Natural-Pigment-Creator",
      "",
      "N",
      "N",
      "pigment, color, utilization, resource, material",
      "fabrication, sensors, biomedia",
      "",
      "complete",
      "Zhu Zihan",
      "InkWare is a natural ceramic pot that takes everyday vegetables, plants,and natural resources, and spins them into beautiful coloured mediums to be used for experimental art making（Pigment extraction does not require the use of special materials, operating a high degree of freedom）"
    ],
    [
      "Daily Petri Dish",
      "San Francisco",
      "Klari Reis",
      "2013~2021",
      "https://honestlywtf.com/art/daily-petri-dish/",
      "art within the confines of plexiglass petri dishes",
      "N",
      "N",
      "pigment, color, material",
      "fabrication, data",
      "paintings",
      "complete",
      "Zhu Zihan",
      "Klari uses layers of reflective epoxy polymer to create colorful and abstract paintings that look like living microorganisms."
    ],
    [
      "#CarbonFeed",
      "Initial installation at the University of Virginia",
      "Jon Bellona and John Park",
      "2014",
      "https://carbonfeed.org/",
      "data visualization",
      "N",
      "N",
      "carbon, footprint, sound",
      "sensors, coding, fabrication, digital fabrication, sound, data",
      "social media, virtuality",
      "speculative",
      "Chen Jing",
      "the work reveals the environmental cost of online behavior"
    ],
    [
      "inaho",
      "uk",
      "Tangent",
      "2013",
      "https://www.designboom.com/design/inaho-interactive-robotic-light-lexus-design-award-2013/",
      "installation",
      "N",
      "N",
      "Bionic, more-than-human, landscape, light",
      "sensors, data, coding, fabrication, digital fabrication",
      "",
      "complete",
      "Song Yue",
      "The motion of a swinging ear of rice is not something the plant makes by itself, but a passive motion that is created by wind, which is soothing."
    ],
    [
      "communifeet",
      "japan",
      "Taku",
      "2014",
      "https://www.designboom.com/project/communifeet/",
      "concept",
      "N",
      "N",
      "temperature, more-than-human",
      "fabrication, data, sensors, coding",
      "",
      "prototype",
      "",
      "a way to use five senses"
    ],
    [
      "airpiano",
      "data 404",
      "omer yosha",
      "",
      "https://www.designboom.com/technology/omer-yosha-airpiano-at-dmy-berlin-design-festival-09/",
      "",
      "N",
      "N",
      "sound, utilization, air",
      "fabrication, digital fabrication, sound, data, coding, sensors",
      "",
      "complete",
      "Dong Zixuan"
    ],
    [
      "arduino ant farm",
      "",
      "adam franchino",
      "",
      "https://www.designboom.com/art/adam-franchino-arduino-ant-farm/",
      "",
      "N",
      "N",
      "ant, sound, insect, animals",
      "sound, data, sensors, fabrication, coding",
      "",
      "speculative",
      "Dong Zixuan"
    ],
    [
      "wind-responsive color lights",
      "",
      "GwaGwa",
      "",
      "https://www.designboom.com/art/gwagwa-colors-of-the-windway-japanese-waterfront-wind-responsive-color-lights-12-02-2014/",
      "",
      "Y",
      "N",
      "wind, light, waterscape, utilization, sea",
      "fabrication, sensors, data, digital fabrication",
      "",
      "complete",
      "Dong Zixuan",
      "The color of wind"
    ],
    [
      "man made moon",
      "UK",
      "Sam Jacob",
      "2012",
      "https://www.dezeen.com/2012/11/17/man-made-moon-by-sam-jacob/",
      "concept art",
      "Y",
      "N",
      "moon, biorhythm",
      "fabrication, data, digital fabrication",
      "",
      "complete",
      "Guo Qingqing",
      "mimic the moon phases on a rooftop"
    ],
    [
      "human-cloud",
      "",
      "Filips Staņislavskis",
      "2021",
      "https://www.dezeen.com/2021/10/21/human-cloud-project-filips-stanislavskis-geoengineering/",
      "Eindhoven graduation project",
      "Y",
      "N",
      "cloud, air",
      "fabrication, biomedia",
      "",
      "speculative",
      "Guo Qingqing",
      "turns human breath into clouds"
    ],
    [
      "tumbleweed desert",
      "israel",
      "Shlomi Mir",
      "",
      "https://www.designboom.com/project/tumbleweed-desert/",
      "",
      "N",
      "N",
      "desert, wind, degrading, rewild",
      "fabrication, digital fabrication, data, sensors",
      "",
      "prototype",
      "Dong Zixuan"
    ],
    [
      "Natural Capital",
      "Milan, Italy",
      "Carlo Ratti in collaboration with ENI",
      "2021",
      "https://www.dezeen.com/2021/09/15/carlo-ratti-associati-partners-oil-company-milan-design-week-2021/",
      "installation for milan design week 2021",
      "N",
      "N",
      "climate change, co2, multi-species, plants, air, carbon",
      "fabrication, digital fabrication, data, sensors",
      "",
      "complete",
      "Zhou ZiYin",
      "The Natural Capital installation features large bubbles suspended next to different plant species, detailing how much carbon dioxide they absorb from the atmosphere."
    ],
    [
      "Data Sonification Archive",
      "Northeastern University, College of Arts, Media & Design",
      "Lenzi S., Ciuccarelli P., Liu H., Hua Y.",
      "2020",
      "https://sonification.design/",
      "web-repository of projects related to data sonification world",
      "N",
      "N",
      "sound, resource, environment",
      "sound, data, sampling, sensors",
      "",
      "complete",
      "Licari Giorgia",
      "This projects-repository helps to discover the data visualization combined with sound output in complmenting other modes of rapresentation. Indeed,  with visualization still being one of the prominent forms of data transformation, sound can enrich the experience of data through less explored senses."
    ],
    [
      "The book of life",
      "Moleskine Foundation",
      "Lupi Giorgia",
      "2022",
      "http://giorgialupi.com/moleskine-foundation",
      "artistic book created for Moleskine Foundation ",
      "N",
      "N",
      "regenerate",
      "fabrication",
      "",
      "complete",
      "Licari Giorgia",
      "The \"Book of Life\" artwork by G. Lupi was used to describe the details (perceived or not) of our daily lives, revealing hidden patterns that make us who we are thanks to series of colourful stitches one for each day."
    ],
    [
      "The deep sea",
      "",
      "Agarwal Neal",
      "2022",
      "https://neal.fun/deep-sea/",
      "interactive website",
      "N",
      "N",
      "sea, multi-species",
      "digital fabrication, data",
      "deep sea",
      "complete",
      "Licari Giorgia",
      "Immersive website to communicate the age of the related stromatolites in correlation with timw by scrolling down "
    ],
    [
      "Interwoven",
      "Amsterdam",
      "Diana Scherer",
      "since2016",
      "https://dianascherer.nl",
      "Diana Scherer trains the roots of plants to grow in intricate structures, creating a 3D textile. When the roots are fully grown, she removes them from the soil and cuts off the plant stems. The pieces produced are not yet suitable to be worn, but hint at a potential, more sustainable future in which we grow our own fashion in the ground.",
      "N",
      "N",
      "multi-species, grass, utilization, resource, root",
      "fabrication, digital fabrication, coding, biomedia",
      "",
      "complete",
      "",
      "it shows a possible image of how Biomedia could be applied and appear."
    ],
    [
      "PlantFiction",
      "London",
      "Torika",
      "2011",
      "http://troika.uk.com/wp-content/uploads/2015/07/catalogue-3.pdf",
      "The title, ‘Plant Fiction’ layers facts, fiction, myth, history, radical thinking and researches our present-day relation- ship with nature and culture, green and the city. Five sce- narios, each formed around a fictitious plant species are placed on location in a London of the near-future. Each kind is utilized to improve a familiar man-made condi- tion. In these near-future scenarios Troika imagined plants that would self-decompose in gain of biofuels, plants that excrete unique pigments to be implemented in security devices, creepers that can sense air-borne viruses and plants that reclaim gold from electronic circuits found in landfills, thus evoking prospective scenarios while uncover- ing our often short-sighted and utilitarian view on nature and mankind’s relationship to it.\nPlant Fiction was purchased for the permanent col- lections of he Art Institute of Chicago and the Israel Museum, Jerusalem.",
      "Y",
      "N",
      "biodiversity, multi-species, pollution, resource",
      "fabrication, biomedia",
      "",
      "speculative",
      "",
      "it provokes a reflection about nowdays prevailing, short-sighted, utiltarian view on nature and mankind's relationship to it."
    ],
    [
      "The syntheic kindom: A Natural History of the Synthetic Future",
      "London",
      "Alexandar Daisy Ginsberg",
      "2009",
      "https://www.daisyginsberg.com/work/synthetic-kingdom",
      "The speculative future of synthetic biology",
      "N",
      "N",
      "multi-species, synthetic biology, biodiversity",
      "fabrication, biomedia",
      "",
      "speculative"
    ],
    [
      "E.chromi",
      "London",
      "Alexandar Daisy Ginsberg, James King, 2009 Cambridge iGem team",
      "2009",
      "https://www.daisyginsberg.com/work/echromi-living-colour-from-bacteria",
      "The Scatalog imagines using it for cheap, personalised disease monitoring. Engineered bacteria, ingested in yoghurt, would colonise our gut, keeping watch for the chemical markers of diseases. If disease is detected, the bacteria produce an easy-to-read warning by colouring your poo. The Scatalog was made as a tool for critical discourse in synthetic biology and was first presented at iGEM in 2009.",
      "N",
      "N",
      "multi-species, bacteria, micro-organisms, utilization, resource, synthetic biology, color, pigment, waste, hygenine",
      "fabrication, biomedia",
      "",
      "speculative"
    ],
    [
      "The Supertask",
      "UK",
      "Alexandar Daisy Ginsberg, Sascha Pohflepp",
      "2011",
      "https://www.daisyginsberg.com/work/the-supertask",
      "Daily weather forecasts are the product of sophisticated, yet reductionist models of the climate, and result in a representation of reality: a number in degrees. Using mechanical climate control, we materialised the deviation between model and reality by simulating the temperature for that time and place, as predicted 24 hours earlier. The visitor could experience the computational model inside, and by stepping outside, feel any deviation from reality. ",
      "N",
      "N",
      "temperature, environment, weather",
      "fabrication, sensors",
      "",
      "complete"
    ],
    [
      "Growth Assembly",
      "London",
      "Alexandar Daisy Ginsberg, Sascha Pohflepp",
      "2009",
      "https://www.daisyginsberg.com/work/growth-assembly",
      "Synthetic biology enabled us to harness our natural environment for the production of things. Coded into the DNA of a plant, product parts grow within the supporting system of the plant's structure. When fully developed, they are stripped like a walnut from its shell or corn from its husk, ready for assembly.\nShops evolved into factory farms, with licensed products grown where sold. Large items take time to grow and are more expensive while small ones are more affordable. The postal service delivers lightweight seed-packets for domestic manufacturers.",
      "Y",
      "N",
      "multi-species, utilization, plants, resource, agriculture",
      "fabrication, biomedia",
      "",
      "speculative",
      "",
      "Using biology for the production of consumer goods has reversed the idea of industrial standards, introducing diversity and softness into a realm that once was dominated by heavy manufacturing.\n\nThe product shown here is the Herbicide Sprayer, an essential commodity used to protect delicate engineered horticultural machines from older nature that can naturally defend itself."
    ],
    [
      "Seasons of the Void",
      "Paris",
      "Alexandar Daisy Ginsberg, Sascha Pohflepp, Andrew Stellitano",
      "2013",
      "https://www.daisyginsberg.com/work/seasons-of-the-void",
      "Seasons of the Void imagines delicious fruits that are grown from redesigned yeast, gorging on electricity instead of sunlight. As the ship flies away from the Sun, electrosynthesis replaces photosynthesis. Here, farming would rely less on Earth’s seasons than on magnetic fields thrown out by solar storms. ",
      "N",
      "N",
      "multi-species, synthetic biology, outerspace, food, electrosynthesis",
      "fabrication",
      "",
      "speculative"
    ],
    [
      "Designing for the Sixth Extinction",
      "",
      "Alexandar Daisy Ginsberg",
      "2013-2015",
      "https://www.daisyginsberg.com/work/designing-for-the-sixth-extinction",
      "In this version of the future, novel companion species are designed by synthetic biologists to support endangered natural species and ecosystems. Financed by corporate biodiversity offset schemes, these patented species are released into the wild. They compensate for biodiversity lost due to monoculture farming of biomass for biofuel and chemical production. For a thriving bioeconomy, the preservation of natural biodiversity is worthwhile not just for sentimental reasons, it is also a valuable DNA library for future biological designs.\nModeled on fungus, bacteria, invertebrates and mammals, the fictional designed species are ecological machines that fill the void left by vanished organisms, or offer novel protection against more harmful invasive species, diseases and pollution.",
      "N",
      "N",
      "preservation, conservation, synthetic biology, extinction, biodiversity, rewild",
      "biomedia, sensors, coding, fabrication, biotech",
      "",
      "speculative"
    ],
    [
      "Pollinator Pathmaker",
      "London",
      "Alexandar Daisy Ginsberg",
      "2021",
      "https://pollinator.art",
      "Simply follow the steps in the algorithmic toolbox to select your garden conditions and play with how the algorithm solves the problem of empathy. The algorithm choose and arrange from a curated palette of locally appropriate plants. Every garden it generates is different, but each is computed to support the maximum pollinator species possible.",
      "Y",
      "Y",
      "biodiversity, pollinator, garden, plants, flower, insect",
      "AI, data",
      "customization",
      "complete",
      "",
      "Pollinator Pathmaker is a response to human-made ecological damage. By creating for other species, it uses art to give us empathy and agency to care for them. Whether you’re a beginner or experienced gardener, join us in this art-led campaign to create the world’s largest climate-positive artwork together."
    ],
    [
      "The Wilding of Mars",
      "UK",
      "Alexandar Daisy Ginsberg",
      "2019",
      "https://www.daisyginsberg.com/work/the-wilding-of-mars",
      "The Wilding of Mars simulates the growth of a planetary wilderness, seeded with Earth life forms -- plants, not human.",
      "N",
      "N",
      "plants, more-than-human, colonisation, planet, indigenous life, invasive species",
      "coding, digital fabrication",
      "",
      "complete"
    ],
    [
      "The Substitute",
      "UK",
      "Alexandar Daisy Ginsberg",
      "2019",
      "https://www.daisyginsberg.com/work/the-substitute",
      "A northern white rhino is digitally brought back to life, informed by developments in the human creation of artificial intelligence (AI). Based on research from AI lab DeepMind, the rhino performs as an artificial agent, an autonomous entity that learns from its environment. A life-size projection, 5m wide, shows the artificial rhino roaming in a virtual world, becoming more “real” as it comprehends the limits of the space. As the artificial rhino habituates to its space, its form and sound toggle from pixelation to lifelike—reminding the viewer that this living, breathing rhino, coming to life without its natural context, is entirely artificial.",
      "N",
      "N",
      "multi-species, extinction, environment, habitat, rhino",
      "AI, virtual reality, digital fabrication",
      "",
      "complete"
    ],
    [
      "Resurrecting the sublime",
      "UK",
      "Alexandar Daisy Ginsberg",
      "2019",
      "https://www.daisyginsberg.com/work/resurrecting-the-sublime",
      "Using genetic engineering to resurrect the smell of extinct flowers—so that humans may again experience something we have destroyed—is awesome and perhaps terrifying. This dizzying feeling evokes the sublime, an “expression of the unknowable”, an aesthetic",
      "N",
      "N",
      "multi-species, extinction, smell, plants, flower",
      "biotech, digital fabrication, biotech, sampling",
      "synthetic biology tech",
      "complete"
    ],
    [
      "Machine Auguries",
      "UK",
      "Alexandar Daisy Ginsberg",
      "2019",
      "https://www.daisyginsberg.com/work/machine-auguries",
      "In the installation, a natural dawn chorus is taken over by artificial birds, their calls generated using machine learning. Solo recordings of chiffchaffs, great tits, redstarts, robins, thrushes, and entire dawn choruses were used to train two neural networks, pitted against each other to sing (a Generative Adversarial Network, or GAN). Reflecting on how birds develop their song from each other, a call and response of real and artificial birds spatialise the evolution of a new language. Samples taken from each stage in the GAN’s training revealing the artificial birds’ growing lifelikeness. ",
      "Y",
      "N",
      "bird, multi-species, sound",
      "biotech, digital fabrication, biotech, sampling",
      "synthetic biology tech",
      "complete"
    ],
    [
      "Outside/Inside",
      "",
      "Gaurav Wali",
      "2021",
      "https://www.gauravmkwali.com/outside-inside",
      "An unsusal holder of inventory made of pine needles",
      "N",
      "N",
      "utilization, material, plants, pine",
      "biomedia",
      "",
      "complete"
    ],
    [
      "Augmented Grounds",
      "Québec, Canada",
      "Soomeen Hahm (SoomeenHahm Design Ltd / SCI-Arc)\nYumi Lee (Seoul National University)\nJaeHeon Jung (KOH SX Studio Inc.)\nHanjun Kim (SoomeenHahm Design Ltd)",
      "2021",
      "https://dataidedesign.com/augmented-grounds-introducing-smart-construction-technology-using-augmented-reality/",
      "Using AR to build landscape",
      "Y",
      "N",
      "garden, landscape",
      "augmented reality, digital fabrication",
      "",
      "complete",
      "",
      "possible way of applying AR to building urban nature."
    ],
    [
      "Rewild Clock",
      "Chester, England",
      "Jack Hardiker",
      "2022",
      "https://www.deeside.com/chesters-eastgate-clock-rewilded-using-augmented-reality/",
      "Using AR to show a rewilded urban scene",
      "Y",
      "N",
      "rewild, plants, landscape",
      "augmented reality",
      "",
      "complete"
    ],
    [
      "Tree Equity Score",
      "",
      "-",
      "-",
      "https://www.treeequityscore.org",
      "Collecting, analysing and disseminating data of urban tree distribution to build a tool to create Tree equity across USA",
      "Y",
      "N",
      "tree, natural benefit, resource, environment",
      "data",
      "tree equity",
      "complete"
    ],
    [
      "Cultivating Frequencies",
      "California, USA",
      "Colin Honigman, ACCD faculty et al",
      "2014",
      "https://colinhonigman.com/Cultivating-Frequencies",
      "Cultivating Frequencies transforms a garden into an interactive and generative musical installation by analyzing data from the garden and translating them into musical components. ",
      "N",
      "N",
      "multi-species, symbiosis, plants, sound, ecosystem, environment, soil, garden, temperature, bionic, biorhythm",
      "data, fabrication, coding, digital fabrication",
      "interaction",
      "complete"
    ],
    [
      "Regional AlgaeFarm",
      "Simrishamn, Sweden ",
      "Ecologic Studio",
      "2011",
      "https://www.ecologicstudio.com/projects/reg-algaefarm",
      "-the actual algae garden, the algae can be cultivated by the visitors by blowing co2 in the photo-bioreactor bags, observe the diverse colours as well as the different ecologies of micro or macro algae with magnifying lenses and finally interact via LED responsive memory system.- the regional co-action plan is presented via a map on the floor below the garden as well as a Touristic Map of the region presenting the master plan as well as the different type of algae and topographic region which is possible to find at the moment on the local landscape and the proposed prototype that could be develop from these resources.",
      "N",
      "N",
      "agriculture, algae, micro-organisms, utilization, resource, food, waterscape, co2",
      "coding, fabrication, biomedia",
      "",
      "prototype"
    ],
    [
      "Airbubble",
      "Warsaw, Poland",
      "Ecologic Studio",
      "2021",
      "https://www.ecologicstudio.com/projects/airbubble-playground-and-exhibition",
      "biotechnological playground to integrate air-purifying micro-algae.",
      "Y",
      "N",
      "air, pollution, algae, utilization, co2",
      "fabrication, biomedia",
      " interaction, playground(kids)",
      "complete",
      "",
      "Kids interact/play with the algae with a simultaneous impact of cleaning the urban air, which is a good lesson for kids about connecting with nature."
    ],
    [
      "Deep Green | Urbansphere",
      "",
      "Ecologic Studio",
      "2021",
      "https://www.ecologicstudio.com/projects/deep-green-urbansphere-venice",
      "This project showcases ecoLogicStudio's recent work on the future of green urban planning, combining artificial intelligence with big data analysis. It also features a unique insight in the infrastructural logics of the Venetian canal system with a speculative AI video simulation, illustrating the accelerated evolution of the Venetian urban fabric over the course of the next 250 years.",
      "Y",
      "N",
      "slime mould, micro-organisms, landscape, utilization",
      "AI, data, biomedia",
      "urban planning",
      "prototype"
    ],
    [
      "Otrivin Air Lab",
      "Lodon",
      "Ecologic Studio",
      "2022",
      "https://www.ecologicstudio.com/projects/otrivin-air-lab",
      "AIRlab is an urban laboratory for converting air pollution into products that help protect our breathing.",
      "Y",
      "N",
      "air, multi-species, micro-organisms, food, utilization, algae, resource, material, agriculture, carbon, fertilizer",
      "biomedia, data, coding, digital fabrication, fabrication",
      "circular economy",
      "prototype"
    ],
    [
      "GAN-Physarum / Deep Green",
      "Lodon",
      "Ecologic Studio",
      "2021/2022",
      "https://www.ecologicstudio.com/projects/gan-physarum-la-derive-numerique",
      "A trained machine learning algorithm that behaves like a living Slime Mould and depicts the future of a bio-digital autonomous Paris.\n/\nDeepGreen is a long-term project developed by ecoLogicStudio with UNDP (United Nations Development Programme) combining AI and big data analysis. The project aims at designing systemic cities that use their size and collective energy to offer refuge for both humans and displaced wildlife, that promote the emergence of positive microclimate, that replenish depleted water sources and that restore degraded terrains, pushing back on processes such as desertification, land erosion and contamination.",
      "Y",
      "N",
      "slime mould, micro-organisms, landscape, utilization",
      "AI, data, biomedia, sensors, sampling, coding, biotech",
      "urban planning, machine learning",
      "prototype"
    ],
    [
      "Rhapsody for an Expanded Biotechnological Apparatus",
      "NY, USA",
      "Laura Splan",
      "2022",
      "https://www.laurasplan.com/rhapsody-for-an-expanded-biotechnological-apparatus",
      "It is a tactile sound installation located in the elevator of the Tang Teaching Museum that connects hidden artifacts of science to familiar domains of the everyday. The installation reenvisions the elevator as a biological cell and its visitors as proteins as they are prompted to engage with a haptic textiles sculpture while listening to a sonic tour of a biotech laboratory.",
      "Y",
      "N",
      "cell, more-than-human, sound",
      "fabrication, biomedia",
      "",
      "complete"
    ],
    [
      "Joining Bottles",
      "London",
      "Micaella Pedros",
      "???",
      "https://www.micaellapedros.com/joiningbottles",
      "Joining Bottles is an experimental wood-joining technique using shrunk plastic bottles. \n\nBy heat, a simple plastic bottle is transformed into a wood bonding material offering a meaningful and accessible way to build functional structures. ",
      "N",
      "N",
      "plastic, waste, material, resource, utilization",
      "fabrication",
      "",
      "complete"
    ],
    [
      "OLFi",
      "Sweden",
      "CORNELIA HULLING, YANYI LU, ALEXANDER WIDUA",
      "2021",
      "https://www.biodesignchallenge.org/umea-institute-of-design-2021",
      "OLFi uses the sense of smell to remind users when their smart devices are present. Devices would emit a smell depending on its specific activity.",
      "N",
      "N",
      "smell, micro-organisms, air, synthetic biology, utilization",
      "biomedia, fabrication, sensors",
      "",
      "speculative"
    ],
    [
      "picNYC",
      "USA",
      "haiko cornelissen architecten",
      "2011",
      "https://www.designboom.com/design/haiko-cornelissen-architecten-picnyc/",
      " the grass surface of the furniture allows the urban resident to easily conduct an outdoor-feeling meal indoors. the surreal piece may be altered with the addition of small vegetables or herbs to fit the needs of the table owner as the shape and function of the work is informed by the recently popular cultural movement of urban farming.",
      "Y",
      "N",
      "grass, soil, plants, utilization, material",
      "fabrication",
      "",
      "speculative"
    ],
    [
      "Ecomorphs",
      "???",
      "Luxi Rong and Jianan Shi",
      "2022",
      "http://www.interactivearchitecture.org/lab-projects/ecomorphs",
      "Ecomorphs is an outdoor interactive installation made up of soft robots that are sensitive to their surrounding environment. The team modified 3D printer mechanisms to solder sheets of TPU sheets together into bespoke shapes that define the appearance and embodied performance of the soft robots. The installation utilises a variety of integrated sensing approaches that regulate air pressure inside the robot, detect human gestures, human visual attention, and observers movement around the work. This data is combined to choreograph the motion of the robots mysteriously living deep in a dark forest.",
      "N",
      "N",
      "multi-species, more-than-human, forest",
      "coding, fabrication, digital fabrication, sensors",
      "",
      "prototype"
    ],
    [
      "Vital Morphons",
      "???",
      "Tung and Lynn Nie",
      "2020",
      "http://www.interactivearchitecture.org/lab-projects/vital-morphons",
      "the team questioned what a post-anthropocentric technology might look like, replacing robotics with the material Chitosan to create a kinetic and responsive installation.",
      "N",
      "N",
      "multi-species, more-than-human, material",
      "biomedia, sensors, biotech, biomedia, fabrication",
      "",
      "prototype"
    ],
    [
      "Networking Nature Lecture",
      "Venice",
      "Studio Mobile",
      "2012",
      "http://cargocollective.com/Studiomobile/Networking-Nature",
      "The ecosystem Networking Nature lives off seawater. Within a glass tank filled with salt water, some solar stills extract fresh water by exploiting the heat produced by small lamps. Seawater evaporates and the steam condenses into fresh water, which is collected in tanks and then supplied. However, water is not produced in isolated systems under central control. The new model provides for a large ecological infrastructure as well as small local production units connected to a network able to integrate the production of fresh water and to supply it where needed. It’s a Smart Water Network controlled by sensors that read the local lack of water and, through an Arduino board, activate the pumps providing the water where there is a peak of demand. The Smart Water Network will be a layer of the ecological network as well as the Smart Power Grid and the communications network. This strategy not only gives response to the preservation of the environment, but it is also a radically new model that ensures free and democratic access to the resources to everybody.",
      "Y",
      "N",
      "sea, utilization, resource, preservation, moss, ecosystem",
      "sensors, fabrication",
      "urban farming, installation",
      "speculative"
    ],
    [
      "Jelly Barge",
      "???",
      "Studiomobile",
      "2015",
      "http://cargocollective.com/Studiomobile/Jellyfish-Barge-Expo-2015",
      "Jellyfish Barge is the floating modular greenhouse for urban agriculture that generates its own fresh water and energy, using only solar power. It is an affordable, transportable and replicable solution to grow food within the cities. The strength of its design lies in the concept of combining a food production facility with a vital public space, providing both areas for economic activities and for social interaction. Its multifunctional attitude allows citizens to enjoy a weekly marketplace, allows farmers who manage the structure to rely on a profitable business, and creates resilience and social innovation for the community. All these values augment the attraction, relevance and value of the installation area, acting as the engine of regeneration at a larger scale. Thus, Jellyfish Barge is also a business opportunity for the stakeholders of the building industry. Their involvement is strategic to set the process in motion and guarantees the economic sustainability of the project, in a way that combine the private gains of the market activity with benefits for the local community.",
      "Y",
      "N",
      "food, sea, utilization, resource, agriculture",
      "fabrication",
      "city, module, public space",
      "prototype"
    ],
    [
      "A Dash of  Water/Walthamstow Marshes",
      "UK",
      "Queer Botany",
      "2022/2021",
      "https://www.queerbotany.com/projects",
      "educate people about diverse sextuality/identity with knowledge of botany, reconnecting people with natue.",
      "N",
      "N",
      "multi-species, plants, tree, flower, regenerate",
      "fabrication",
      "identity, sexuality",
      "complete"
    ],
    [
      "The Panda Shop",
      "Dutch",
      "Astrid Birkedal",
      "2020",
      "https://www.designacademy.nl/p/study-at-dae/graduation-show/graduation-projects/astrid-birkedal",
      "visitors to the installation are confronted with a customer-like buying experience, in which they are encouraged to donate to one of China’s giant pandas currently housed in international zoos. The buying process is experienced in six increasingly complicated stages, layering the hard ‘sales pitch’ of commerce over a revelatory exhibition narrative that exposes the realities of Panda Diplomacy.",
      "N",
      "N",
      "multi-species, preservation, animals, extinction, panda",
      "fabrication",
      "panda, politics",
      "complete"
    ],
    [
      "Speculative Communications",
      "Mexico City",
      "Innterspecifics",
      "-",
      "http://interspecifics.cc/comunicacionesespeculativas/",
      "A machine that can observe and learn from a microorganism and uses the data arising from its behavioural patterns as a source of composition for an audio-visual score. This project is focused on the creation of an artificial intelligence that has the ability to identify repeated coordinated actions inside biological cultures. ",
      "N",
      "N",
      "micro-organisms, sound",
      "AI, data, biomedia, sound",
      "",
      "complete"
    ],
    [
      "iOracle",
      "-",
      "Mileece",
      "2018",
      "https://www.mileece.is/ioracle",
      "How do you create a language between human and plants?",
      "N",
      "N",
      "plants, sound, ecology, biorhythm",
      "AI, data, biomedia, sound",
      "",
      "complete"
    ],
    [
      "Pips Plant Parlour",
      "-",
      "Mileece",
      "2018",
      "https://www.mileece.is/pipsplantparlour",
      "participants create unique quadrophonic organic electronic music in an immersive, luminal ,  bio-acoustic bath, all generated from their energetic interaction with plants;\na way to tune into nature, right from the center of the busy metropolis",
      "Y",
      "N",
      "plants, sound, ecology, biorhythm",
      "AI, sensors, digital fabrication, coding, sound",
      "",
      "complete"
    ],
    [
      "Orbia",
      "",
      "Mileece",
      "2018",
      "https://www.mileece.is/orbia",
      "These innovative structures fuse biophilic urban living systems with state-of-the-art interactive immersive audio, imagery and kinetics, integrating functional ecologies within dense urban environments.  When not hosting immersive media content and events for AR, VR and XR, Orbia unites communities with remote ecologies to reignite our connection to nature and one another.",
      "Y",
      "N",
      "plants, sound, ecology, biorhythm",
      "AI, sensors, digital fabrication, coding, sound",
      "",
      "complete"
    ],
    [
      "Mystery Bird",
      "UK",
      "Jack Hardiker",
      "2020",
      "https://jackhardiker.com/Mystery-Bird-AR",
      "Mystery Bird was born in Manchester, before taking flight around the world using Augmented Reality (AR). The project began in the wake of strict social distancing measures. Many of us experienced a renewed interest in our natural surroundings - discerning birdsong again at a time when the world was quietly held at a temporary standstill. Inspired by this, Quays Culture commissioned a group of four artists to create Mystery Bird, an experimental, travelling installation that involves projection, sound and AR.",
      "Y",
      "N",
      "bird, sound, environment",
      "augmented reality, digital fabrication, sound",
      "",
      "complete"
    ],
    [
      "A Vision for the Green Heart of Holland",
      "Holland",
      "The Harrison Studio",
      "1984",
      "https://theharrisonstudio.net/a-vision-for-the-green-heart-of-holland",
      " the Green Heart is now facing encroachment from without and development from within. Its value in 1994-5 was being debated, its identity questioned, its very existence threatened.\nIn responding to this situation the Harrison Studio constructed a series of images–part ceramic tile, part map, part drawing, part video and part discourse. They proposed a new vision for the Green Heart and the Randstad of Holland. In the proposal new boundary conditions emerged that would clarify the roles of the urban, the ecological and the farming communities which altogether comprise a major part of the landscape of Holland.",
      "Y",
      "N",
      "preservation, biodiversity, habitat, symbiosis, landscape",
      "fabrication, data",
      "urban planning",
      "complete"
    ],
    [
      "Greenhouse Britain",
      "UK",
      "The Harrison Studio",
      "2007-2009",
      "https://theharrisonstudio.net/greenhouse-britain-2007-2009",
      "The installation addresses Global Warming from an artist’s perspective. The work proposes an alternative narrative about how people might withdraw as waters rise, what new forms of settlement might look life, and what content or properties a new landscape might have in response to the Global Warming phenomenon. It also demonstrates how a city might be defended.",
      "Y",
      "N",
      "global warming, sea, environment, waterscape",
      "fabrication, data",
      "",
      "speculative"
    ],
    [
      "Root System Drawings Archive",
      "Holland",
      "Wageningen University",
      "-",
      "https://images.wur.nl/digital/collection/coll13/search",
      "",
      "N",
      "N",
      "plants, root, multi-species, biodiversity, tree, resource, grass",
      "data",
      "drawing, documentation",
      "complete"
    ],
    [
      "Deep Time Walk APP",
      "-",
      "-",
      "-",
      "https://www.deeptimewalk.org",
      "Deep Time Walk is a transformative journey through 4.6bn years of Earth history via a 4.6km guided walk. It is an invitation to view the world differently, encouraging positive action and advocacy for a regenerative Earth.\nWe provide tools and resources to empower a global community of changemakers and volunteer facilitators. Our vision is to empower an ensemble of geographically specific and culturally nuanced Deep Time Walks, providing an intercultural story-telling platform that helps bring about a diverse, flourishing ecological civilisation.",
      "N",
      "N",
      "environment, planet, landscape, climate change, rock, stone",
      "data ",
      "",
      "complete"
    ],
    [
      "Biota Beats",
      "USA",
      "EMW Street Bio",
      "-",
      "http://biotabeats.org/index.html",
      "A microbial record player, translating bacteria to sound",
      "N",
      "N",
      "bacteria, micro-organisms, sound",
      "sensors, data, biomedia, sound, fabrication, digital fabrication, biotech, coding",
      "",
      "complete"
    ],
    [
      "Kombucha Sculptures",
      "-",
      "anicka yi",
      "2015",
      "https://www.anickayistudio.biz/artworks/middle-earth-medical",
      "-",
      "N",
      "N",
      "kombucha, micro-organisms, material",
      "biomedia",
      "sclupture, art work, aesthetic",
      "complete"
    ],
    [
      "Kelp Sculptures",
      "",
      "anicka yi",
      "2019",
      "https://www.anickayistudio.biz/artworks/biologizing-the-machine-tentacular-trouble",
      "",
      "N",
      "N",
      "kelp, plants, material, light",
      "biomedia",
      "sclupture, art work, aesthetic",
      "complete"
    ],
    [
      "Fruiting Bodies",
      "",
      "anicka yi",
      "2021",
      "https://www.anickayistudio.biz/artworks/all-islands-are-connected-underwater",
      "",
      "N",
      "N",
      "multi-species, micro-organisms, material, flower",
      "fabrication",
      "sclupture, art work, aesthetic",
      "complete"
    ],
    [
      "Anemone Panels",
      "",
      "anicka yi",
      "2019",
      "https://www.anickayistudio.biz/artworks/i-just-want-to-be-able-to-sleep-at-night",
      "",
      "N",
      "N",
      "multi-species, micro-organisms, material, bacteria, fungi",
      "fabrication",
      "sclupture, art work, aesthetic",
      "complete"
    ],
    [
      "Tempura Fried Flowers",
      "",
      "anicka yi",
      "2011-",
      "https://www.anickayistudio.biz/artworks/the-year-1905",
      "",
      "N",
      "N",
      "flower, material, plants, color",
      "biomedia",
      "sclupture, art work, aesthetic",
      "complete"
    ],
    [
      "Bacteria Lightbox",
      "",
      "anicka yi",
      "",
      "https://www.anickayistudio.biz/artworks/death-grasp",
      "",
      "N",
      "N",
      "bacteria, material, light, color, pigment, fungi, micro-organisms",
      "biomedia",
      "sclupture, art work, aesthetic",
      "complete"
    ],
    [
      "Chicken Skins",
      "",
      "anicka yi",
      "",
      "https://www.anickayistudio.biz/artworks/fish-toffee",
      "",
      "N",
      "N",
      "multi-species, plants, material, color, flower",
      "biomedia, fabrication",
      "sclupture, art work, aesthetic",
      "complete"
    ],
    [
      "Nests",
      "",
      "anicka yi",
      "",
      "https://www.anickayistudio.biz/artworks/escape-from-the-shade-1",
      "",
      "N",
      "N",
      "bee, beehive, multi-species, pollinator, light, color, material",
      "biomedia, fabrication",
      "sclupture, art work, aesthetic",
      "complete"
    ],
    [
      "Bacteria Cultures",
      "",
      "anicka yi",
      "2015",
      "https://www.anickayistudio.biz/artworks/grabbing-at-newer-vegetables",
      "",
      "N",
      "N",
      "bacteria, material, light, color, pigment, fungi, micro-organisms",
      "biomedia, fabrication",
      "sclupture, art work, aesthetic",
      "complete"
    ],
    [
      "Plants Play",
      "Italy",
      "Edo (CEO) & Kika",
      "",
      "https://plantsplay.com",
      "Plants Play is a wearable device that allows you to listen to the Music generated by Plants and Trees. Through two electrodes settled on the leaves, Plants Play converts electrical plant variations into musical notes, and send them by bluetooth on your smartphone. ",
      "N",
      "Y",
      "multi-species, plants, sound, tree, biorhythm",
      "sensors, data, coding, fabrication, sound",
      "",
      "complete"
    ],
    [
      "Human Nature Paintings",
      "",
      "Susan Cohen Thompson",
      "",
      "https://thompsonartstudio.com/human-nature-paintings/",
      "",
      "N",
      "N",
      "plants, color, material, more-than-human, tree",
      "fabrication",
      "paintings",
      "complete"
    ],
    [
      "Adventures with a laser scanner",
      "",
      "Mathias Disney",
      "",
      "http://disneytls.blogspot.com\nhttp://disneytls.blogspot.com/2016/09/face-time.html",
      "Scanning Trees",
      "N",
      "N",
      "tree, environment, air, biodiversity, landscape, co2, forest, tropical forest, climate change",
      "sampling, sensors, coding, digital fabrication",
      "",
      "complete"
    ],
    [
      "Amazon FACE",
      "Brazil",
      "Brazilian Government",
      "",
      "https://amazonface.inpa.gov.br/en/program.php",
      "The central feature of the program is a field experiment of unprecedented scope that will expose an old-growth Amazon forest to the CO2 concentration of the future in an research station near Manaus, Brazil using Free-Air CO2 Enrichment (FACE) technology. ",
      "N",
      "N",
      "tree, environment, air, biodiversity, landscape, co2, forest, tropical forest, climate change",
      "fabrication, sensors, sampling, coding, data",
      "",
      "complete"
    ],
    [
      "GUARDIAN PLATFORM, AudioMoth, Arbimon, Companion,  Uploader",
      "",
      "Rainforest Connection",
      "",
      "https://rfcx.org",
      "Rainforest Connection (RFCx) builds and deploys scalable, open acoustic monitoring systems that can halt illegal logging and poaching, and can enable biodiversity measurement and monitoring.",
      "N",
      "Y",
      "forest, tropical forest, biodiversity, preservation, conservation, sound, animals",
      "sensors, data, AI, fabrication",
      "illegal loggoing, poaching, threat detection, biodiversity monitoring",
      "complete"
    ],
    [
      "Protecting Snow Leopards with Technology",
      "China",
      "Tech4all, HUAWEI",
      "",
      "https://www.huawei.com/en/tech4all/stories/snow-leopard",
      "The MindSpore AI framework is boosting the accuracy and efficiency of analyzing infrared image data to improve conservation of the snow leopard in China's Qinghai-Tibet Plateau",
      "N",
      "N",
      "animals, preservation, conservation, leopard, extinction",
      "AI, sensors, data",
      "",
      "complete"
    ],
    [
      "Saving Norway's Endangered Atlantic Salmon",
      "Norway",
      "Tech4all, HUAWEI",
      "2021",
      "https://www.huawei.com/en/tech4all/stories/saving-the-atlantic-salmon-in-norway",
      "Artificial intelligence are protecting the wild Atlantic salmon from being overwhelmed by its invasive Pacific cousin",
      "N",
      "N",
      "multi-species, preservation, conservation, salmon, invasive multi-species, ecosystem, animals, food, waterscape",
      "AI, sensors, digital fabrication",
      "",
      "complete"
    ],
    [
      "Creating A Tech Safety Net Because My Neighbors Are Elephants",
      "China",
      "Tech4all, HUAWEI",
      "2019",
      "https://www.huawei.com/en/tech4all/stories/asian-elephants",
      "Deploying China's first connected Asian Elephant protection, monitoring, and warning system",
      "N",
      "N",
      "multi-species, preservation, conservation, elephant, extinction",
      "AI, sensors, data",
      "",
      "complete"
    ],
    [
      "Smart Whale Sounds",
      "Ireland",
      "Tech4all, HUAWEI",
      "2021",
      "https://www.huawei.com/en/tech4all/stories/sound-of-whales",
      "Smart technology deployed off the Irish south coast can mean the difference between life & death for aquatic mammals",
      "N",
      "N",
      "multi-species, preservation, conservation, whale, sea, animals, sound, pollution, dolphin, extinction, environment, waterscape",
      "AI, sensors, data, sound",
      "machine learning",
      "complete"
    ],
    [
      "Calling Tree",
      "UK",
      "Rosemary Lee & Simon Whitehead",
      "2014-",
      "https://www.artsadmin.co.uk/project/calling-tree/",
      "Located in and around a mature tree in a significant site, and working with a team of aerialists, singers and performers they have created a durational performance made up of cycles of songs, movement and messages.",
      "Y",
      "N",
      "tree, sound, symbiosis, more-than-human",
      "fabrication, sound",
      "community",
      "complete"
    ],
    [
      "Inca Whistling Vessels",
      "Peru",
      "",
      "",
      "https://www.youtube.com/watch?v=d_BvHJXIAQs",
      "",
      "N",
      "Y",
      "multi-species, material, sound, animals",
      "fabrication, sound",
      "",
      "complete"
    ],
    [
      "Algaculture",
      "UK",
      "Michael Burton & Michiko Nitta",
      "2010",
      "https://www.burtonnitta.co.uk/Algaculture.html",
      "Algaculture designs a new symbiotic relationship between humans and algae. It proposes a future where humans will be enhanced with algae living inside new bodily organs, allowing us to be semi-photosynthetic. Almost enabling us to become plant-like by gaining food from light. As such, we will be symbionts (meaning that both entities entirely depend on each other for survival), entering into a mutually beneficial relationship with the algae.",
      "N",
      "N",
      "food, symbiosis, algae, resource, more-than-human, co2, utilization",
      "fabrication",
      "",
      "speculative"
    ],
    [
      "The Algae Opera",
      "UK",
      "Michael Burton & Michiko Nitta",
      "2012",
      "https://www.burtonnitta.co.uk/AlgaeOpera.html",
      "The algae, which are a photosynthetic plant-like organism, feeds on the carbon dioxide in the singer’s breath. As an important future food source, the singer’s algae can also be eaten. Alongside listening to her music, the audience can also taste her song.",
      "N",
      "N",
      "food, symbiosis, algae, resource, more-than-human, co2, utilization, sound",
      "fabrication",
      "",
      "speculative"
    ],
    [
      "Instruments of the Afterlife",
      "UK",
      "Michael Burton & Michiko Nitta",
      "2015",
      "https://www.burtonnitta.co.uk/InstrumentsOfTheAfterlife.html",
      "Instruments are created to transform contamination into valuable materials, by employing plants and engineered bacteria.\n\nInstead of mining material from geological sources and using fossil fuels, that lead to environmental harm, could future generations use the contamination and pollution we leave behind to build their future world? Can they build balanced relationships with the natural world to be a no-waste civilisation?",
      "N",
      "N",
      "pollution, micro-organisms, material, utilization, plants, bacteria, waste",
      "fabrication, biotech",
      "synthetic biology tech",
      "speculative"
    ],
    [
      "Shadow Biosphere",
      "UK",
      "Michael Burton & Michiko Nitta",
      "2011",
      "https://www.burtonnitta.co.uk/shadowbiosphere.html",
      "Man-made biodiversity to recover Earth’s lost species.\nClimate change, a human population of 9 billion, the effects of deforestation and rising oceans will drive species to extinction. Scientists say three species of organisms become extinct every hour due to environmental pressures created by humans. Biodiversity is not just a green issue. It is vital as a life support system and we simply cannot exist without rich biodiversity. If we don’t act now, we will loose organisms which might become a solution to unforeseen disasters and diseases.",
      "N",
      "N",
      "multi-species, synthetic biology, biodiversity, extinction, regenerate",
      "fabrication, biotech",
      "",
      "speculative"
    ],
    [
      "Altered Ways of Being",
      "UK",
      "Michael Burton & Michiko Nitta",
      "2013",
      "https://www.burtonnitta.co.uk/AlteredWaysofBeing.html",
      "See with the skin, smell with suckers, change colour for social interactions and sense the world with a brain distributed across the body.\n\nThese abilities possessed by an octopus shape a mind that is possibly one of the most different non-human forms of intelligence to our own. Altered Ways of Being takes inspiration from the octopus to reveal links between our own human body and mind.",
      "N",
      "N",
      "multi-species, octopus, more-than-human, animals, color, light, bionic, smell",
      "fabrication",
      "",
      "speculative"
    ],
    [
      "Driade: the voice of nature",
      "Italy",
      "Alessia Pinna, Clarissa Cuoccio, Heitor Lobo Campos, Innocenzo De Risola, Mika Lessmann",
      "2022",
      "https://www.design.polimi.it/fileadmin/user_upload/eventi/2022/img_2022/Thackara/G02_cover.pdf",
      "sensor, data, coding, fabrication, sound",
      "Y",
      "N",
      "tree, sound, biorhythm",
      "sensors, coding, fabrication, sound",
      "",
      "prototype"
    ],
    [
      "Micro detective",
      "Italy",
      "Julian de Freitas, Leo Olivier Ocando, Max Park, Joshua Seckerdieck.",
      "2022",
      "https://www.design.polimi.it/it/lista-eventi/dettaglio-eventi?tx_news_pi1%5Baction%5D=detail&tx_news_pi1%5Bcontroller%5D=News&tx_news_pi1%5Bnews%5D=492&cHash=f7f48ac17cfe39c1a5a09f64986116be",
      "Simple DIY construction of a makeshift microscope encourages urbanites to collect and observe microbial samples. An app records the microscope sessions, with AI included in to recognize and classify the observed species. Finally, translation of microscopic data allows diving into the microbial sample in an immersive VR experience.",
      "Y",
      "Y",
      "micro-organisms, multi-species, biodiversity",
      "AI, sensors, coding, virtual reality, fabrication, sampling",
      "",
      "prototype"
    ],
    [
      "Bird Hospitality service in the Bovisa Campus",
      "Italy",
      "Isabelle Erdmann, Jisoo Kim, Joseph Varanese, Jing Zhang, Siddhant Bothra.",
      "2022",
      "https://www.design.polimi.it/it/lista-eventi/dettaglio-eventi?tx_news_pi1%5Baction%5D=detail&tx_news_pi1%5Bcontroller%5D=News&tx_news_pi1%5Bnews%5D=492&cHash=f7f48ac17cfe39c1a5a09f64986116be",
      "The project explores the design of connected micro-environments for birds that are placed on the empty balconies of district 9 of Milan, citizens can become volunteers by hosting the birds ‘suite cabins’, which allows being a member of a specific digital community that brings together the passion of bird lovers and the ecologist expertise. These product-service solutions aim to increase and restore biodiversity in the locality and find new relations between human-animal interactions.",
      "Y",
      "Y",
      "bird, habitat, environment, animals",
      "sensors, fabrication",
      "",
      "prototype"
    ],
    [
      "Sweet City",
      "Costa Rica",
      "Curridabat",
      "",
      "https://www.theguardian.com/environment/2020/apr/29/sweet-city-the-costa-rica-suburb-that-gave-citizenship-to-bees-plants-and-trees-aoe",
      "Sweet City is just one of a number of biocorridors around the country that allow the genetic spread of species to maintain their strength.",
      "Y",
      "N",
      "pollinator, plants, indigenous life, habitat, ecosystem",
      "fabrication",
      "citizenship, urban planning, green infrastructure",
      "complete"
    ],
    [
      "Botanical chalking",
      "Europe",
      "-",
      "2001-",
      "http://sauvagesdemarue.mnhn.fr/index.html\nhttps://morethanweeds.co.uk\nhttps://www.brut.media/fr/nature/toulouse-ce-botaniste-trace-a-la-craie-le-nom-des-plantes-sauvages-f1bbaded-03d9-4f27-9f66-f7bbea25df31\nhttps://www.tela-botanica.org",
      "Several projects, including: chalking names of different plants in urban area, citizen science projects collaborating with citizens to record species in cities",
      "Y",
      "Y",
      "multi-species, plants, biodiversity",
      "sampling, fabrication, data",
      "photography",
      "complete"
    ],
    [
      "Symbiosis",
      "USA",
      "STOWE HAMMARBURG, DANIEL KIM, YOOYOUNG KO, ZACHARY SCHWEMLER & JESSICA SHEN",
      "2016",
      "https://www.biodesignchallenge.org/cmu",
      "A bioengineered plant that releases caffeine into the air during the day and melatonin at night, Symbiosis is a critique of the way modern technology has influenced our sleep patterns.",
      "Y",
      "N",
      "biorhythm, environment, plants, symbiosis",
      "fabrication, biotech, biotech",
      "sleep, synthetic biology tech",
      "prototype"
    ],
    [
      "Kelsun",
      "USA",
      "Tessa Callaghan, Aaron Nesser, Aleks Gosiewski",
      "2016",
      "https://www.keellabs.com",
      "Kelsun™ is a seaweed-based yarn with a significantly lower environmental footprint than legacy fibers",
      "N",
      "N",
      "kelp, material, resource, utilization, footprint",
      "biomedia",
      "fabrics",
      "complete"
    ],
    [
      "Starter Culture",
      "USA",
      "GAGE BRANDA, SARAH WHELTON, JAKE O'HAGAN, EMMA WHITLOCK",
      "2016",
      "https://www.biodesignchallenge.org/mica2016",
      "A biomaterials starter kit designed to introduce makers to the expansive world of biomaterials, the contents of the Starter Culture kit, which include bioplastics, mycelium and silk proteins, can be propagated and shared among makers",
      "N",
      "N",
      "material, mycellium, silk, micro-organisms",
      "biomedia, biotech, fabrication",
      "",
      "prototype"
    ],
    [
      "Mutua",
      "USA",
      "MUN YI CHENG, CALEB FISHER, FANGYUAN HU, BRENDAN HO, RYAN ODOM, ANTHONY STOFFELLA & XIANGTIA SUN",
      "2016",
      "https://www.biodesignchallenge.org/sci-arc",
      "A panel inside homes on which organisms like lichen or slime mold grow and behave as biosensors and living art, Mutua offers a fresh, living concept for interior design.",
      "N",
      "N",
      "micro-organisms, utilization, material, color, pigment, slime mould",
      "biomedia, fabrication",
      "",
      "prototype"
    ],
    [
      "Growing Buildings ",
      "USA",
      "-",
      "2016",
      "https://www.biodesignchallenge.org/sci-arc",
      "Pairing drones with living organisms, Growing Buildings seeks to heal urban infrastructure with bacteria and slime mold that produce organic sealants.  ",
      "Y",
      "N",
      "micro-organisms, utilization, material, slime mould, bacteria",
      "biomedia, fabrication",
      "construction repair",
      "prototype"
    ],
    [
      "MyoTomato",
      "USA",
      "LEMAN AKPINAR, VIKTOREA BENOIS, SEBASTIAN COCIOBA, ANDREW CZIRAKI, DAVID HANLON, MARGUERITE LI, BO LIU, STEPH MANTIS, KIRIN PINO, SHANNON POLLAK, GINA PROENZA, TARAH RHODA, VICTOR TABOADA, DARYA WARNER, JOHN WELLS",
      "2016",
      "https://www.biodesignchallenge.org/sva2016",
      "Plants are often deficient in the amounts of protein necessary to sustain the human diet because they are composed mainly of water and starches. To supplement nutrition, MyoTomato proposes bioengineering edible plants to produce myoglobin, a protein normally found in meat. As part of their lab work, the team inserted a DNA sequence naturally found in beef products into a tomato’s genome using agrobacteria.",
      "N",
      "N",
      "multi-species, food, utilization, resource, synthetic biology, agriculture, plants, tomato, animals",
      "biomedia, fabrication, biotech",
      "synthetic biology tech",
      "speculative"
    ],
    [
      "Tumo",
      "USA",
      "-",
      "2016",
      "https://www.biodesignchallenge.org/sva2016",
      "While tumors in animals may be benign or malignant, in plants they may have alternative functions. Bioengineering tumors into plants can rapidly expand the plant's size and therefore possibilities for increased food production. The resulting biomass may not only edible but far more nutritious. Tumo would produce an accelerated crop rich in vitamins, nutrients, and proteins that has a crisp texture and familiar flavors.",
      "N",
      "N",
      "multi-species, food, utilization, resource, synthetic biology, agriculture, plants, animals",
      "biomedia, fabrication",
      "",
      "speculative"
    ],
    [
      "Stabilimentum",
      "USA",
      "MÓNICA BUTLER, REBECCA VAN SCIVER, JIWON WOO",
      "2016",
      "https://www.biodesignchallenge.org/schools/upenn",
      "Latin for support, Stabilimentum is a couture mask that filters air using live spiders and the electrostatic properties of their silk. Inspired by the symbiotic relationship between humans and the microbiome, the fashion accessory creates a symbiosis between human and arachnid.",
      "N",
      "N",
      "spider, eletrostatic, air, symbiosis, multi-species, micro-organisms, pollution, resource, utilization, animals, silk",
      "biomedia, fabrication",
      "",
      "speculative"
    ],
    [
      "Probiome",
      "USA",
      "REBECCA HALLAC, VINCENT SNAGG",
      "2016",
      "https://www.biodesignchallenge.org/schools/upenn",
      "This smart bracelet automatically sprays surfaces with customized probiotics, containing Staphylococcus epidermidis, a bacterial strain that protects the skin from pathogens. The team developed a functional version that pairs with a computer keyboard to prevent MRSA infection in hospitals.",
      "N",
      "N",
      "micro-organisms, skin, hygenine, symbiosis, utilization, bacteria, synthetic biology, resource, material",
      "fabrication, sensors",
      "",
      "prototype"
    ],
    [
      "Life/Light\n",
      "USA",
      "JACOB SULLIVAN, VERONIKA VOLKOVA, RYAN WERTZ, & LOREN BENALLY",
      "2017",
      "https://www.biodesignchallenge.org/arizona-state-university",
      "Life/Light is an integrated system that blurs the boundary between living nature and artifacts. The system provides evening light, energy, and greywater treatment for a human habitat using bioluminescent algae.",
      "Y",
      "N",
      "micro-organisms, utilization, light, algae",
      "fabrication",
      "lighting structure",
      "prototype"
    ],
    [
      "Parturient",
      "USA",
      "LOVISA MINKIEWICZ, JEROEN VAN KEMPEN, & JASMIJN VAN DER WEIDE",
      "2017",
      "https://www.biodesignchallenge.org/artez-institute-of-the-arts",
      "Par-tu-ri-ent imagines a future where pregnancy is one of several ways to carry a child to term. The project considers the social consequences of new reproductive technologies.",
      "N",
      "N",
      "regenerate",
      "fabrication, sensors",
      "fiction",
      "speculative"
    ],
    [
      "Quantworm Mine",
      "UK",
      "LIV BARGMAN AND NINA CUTLER",
      "2017",
      "https://www.biodesignchallenge.org/central-saint-martins",
      "Quantworm Industries is a nanotech wormery housed on former coal mining sites in South Wales that utilizes the earthworm’s natural ability to bio-remediate contaminated soil and bio-synthesize nanoparticles called quantum dots (QDs) from heavy metals. ",
      "N",
      "N",
      "worm, quantum dot, multi-species, pollution, synthetic biology, soil, material, resource, utilization, animals",
      "fabrication",
      "",
      "speculative"
    ],
    [
      "Pink Chicken Project",
      "UK",
      "NONHUMAN NONSENSE\nLEO FIDJELAND & LINNEA VÅGLUND",
      "2017",
      "https://pinkchickenproject.com",
      "Human actions have altered the Earth so profoundly that we have entered a new geological epoch - the Anthropocene. The project suggests genetically modifying a chicken with pink bones and feathers using a gene from the insect cochineal to produce a pigment that will be fossilized when combined with the calcium of the bone. By changing the color of chickens to pink, this project rejects the current violence inflicted upon the non-human world and poses questions of the impact and power of synthetic biology. ",
      "N",
      "N",
      "multi-species, extinction, animals, chicken, pigment, color, more-than-human, synthetic biology",
      "biomedia, fabrication, biotech",
      "anthroprocene, more-than-human, synthetic biology tech",
      "speculative"
    ],
    [
      "PLANETARY PERSONHOOD",
      "Berlin",
      "NONHUMAN NONSENSE",
      "",
      "https://planetarypersonhood.com",
      "As NASA, SpaceX, and others, now attempt to bring earthlings to Mars, Planetary Personhood is an opportunity to free ourselves from the conceptual baggage of earthly traditions and systems. Seeking to move away from the dualistic divide between living beings and inanimate matter, the project invites us to a new way of relating to a planetary whole, and to the myriad of nonhuman forces and actants that surround us.",
      "N",
      "N",
      "planet, rock, more-than-human, utilization, landscape, outerspace",
      "fabrication",
      "decolonisation",
      "speculative"
    ],
    [
      "Tale of a tree human",
      "Östra Vätterbranterna, Sweden",
      "NONHUMAN NONSENSE",
      "",
      "https://nonhuman-nonsense.com/tale-of-a-tree-human",
      "This work is an exploration of how legends and mythology can create long-term family ties to the land and nonhuman beings built on compassion. The tree human Vide is given form in a semi-permanent public sculpture, and was born out of a dialogue with biologists and residents of the UNESCO Biosphere Reserve Östra Vätterbranterna, as part of the project Nature Takes Over by Österängens Konsthall.",
      "N",
      "N",
      "forest, tree, more-than-human",
      "fabrication",
      "legend, mythology, coonection, sculpture, storytelling",
      "complete"
    ],
    [
      "Mosquito Translator",
      "",
      "NONHUMAN NONSENSE",
      "",
      "https://nonhuman-nonsense.com/mosquito-translator",
      "The work consists of an installation, where the audience is presented with a glass chamber full of mosquitos. The chamber has multiple openings/doors, where humans can voluntarily put their hand and arm inside the chamber to meet/feed the mosquitos. Sitting on top of the chamber is the “translator machine”, a device that creates the bridge between mosquitoes and humans, while also being an entity in itself.",
      "N",
      "N",
      "mosquito, animals, food, more-than-human, insect",
      "fabrication, sensors, biomedia",
      "anthroprocene, kinship",
      "speculative"
    ],
    [
      "Audible Flora",
      "",
      "NONHUMAN NONSENSE",
      "",
      "https://nonhuman-nonsense.com/audible-flora",
      "A group of DIY biohackers design a new sensor plant that detects pollution levels and indicates the result in sound to elevate the worsening environmental condition to their fellow citizen. When the plants are put in a beneficial surrounding, they “sing” beautifully. When put in a heavily polluted place, they “scream” a disturbing noise.Initially, the environment improves as people respond to the emotional cues of the plants. However, having found a new niche in which to prosper, the plants eventually mutate and are spread without control, rendering polluted areas uninhabitable by noise. It’s as if nature suddenly has the power to express itself, claiming rights to exist.",
      "N",
      "N",
      "multi-species, synthetic biology, pollution, environment, utilization, sound, plants, invasive multi-species",
      "biomedia, sensors, coding, fabrication, biotech",
      "",
      "speculative"
    ],
    [
      "Human Beeings",
      "",
      "NONHUMAN NONSENSE",
      "",
      "https://nonhuman-nonsense.com/human-beeings",
      "In the face of bee extinction, an alluring plant, that tap into human desires and needs, has started appearing around outdoor gyms. The passing humans drink the plant nectar to replenish their strength. Some pollen sticks in their shirt, and as they drink from the next plant, the vital cross breeding occurs.",
      "N",
      "N",
      "multi-species, food, bee, pollinator, plant, synthetic biology, ecosystem, flower, ecology",
      "biotech, fabrication, biomedia",
      "synthetic biology tech, photography",
      "speculative"
    ],
    [
      "Turn to stone\nBecome stones\nTHE \nANTI-ANTHROPOCENTRIC VENDING MACHINE",
      "",
      "NONHUMAN NONSENSE",
      "",
      "https://nonhuman-nonsense.com/turn-to-stone\nhttps://nonhuman-nonsense.com/becoming-stone\nhttps://nonhuman-nonsense.com/the-antianthropocentric-vending-machine",
      "Human, non-human, boundaries, ineffable.\nA vending machine sells “cures for anthropocentrism”. To obtain the cure you must sacrifice the shiny capsule you just received, breaking it open to reveal a stone that you can eat. The stone is accompanied by a short message, claiming that when you eat this stone, you will never look at stones the same way again. Claiming that stones are not dead, and that you should think about what they want. Thinking about the world differently changes the world. Eating the stone, you become the stone - existence/consciousness is not something exceptionally human.",
      "N",
      "N",
      "stone, rock, food, symbiosis, more-than-human, landscape",
      "fabrication",
      "post-anthroprocentrism, more-than-human",
      "speculative"
    ],
    [
      "Celestial Colony",
      "USA",
      "JONATHAN RANKIN, HUGH PATTON, JONATHAN VISGAITIS, GERALD HOPPER, & JULIEN REMI NGUYEN",
      "2017",
      "https://www.biodesignchallenge.org/kent-state-university",
      "Celestial Colony is a water filter that treats wastewater by pumping it through “algae facets” in a geodesic dome, which filters out nutrients from the water and carbon dioxide from the air. Once the algae has collected the nutrients, it can be used as fertilizer to grow plants within the dome, while the treated water can be reused as greywater or further filtered into potable water.",
      "N",
      "N",
      "algae, waste, waterscape, fertilizer, utilization, co2, plants, resource",
      "digital fabrication, biomedia",
      "",
      "prototype"
    ],
    [
      "POM",
      "UK",
      "GREG ORROM SWAN, LOUIS ALDERSON-BYTHELL, TASHIA TUCKER, & SAM ROOTS",
      "2017",
      "https://www.biodesignchallenge.org/royal-college-of-art",
      "POM lures flies using a controlled release of pheromones from a remote-controlled node, which clusters them around the flowers needing pollination. Nodes distributed throughout the farm enable this ‘cloud of flies’ to be shepherded from one region to another, covering all the blossoms that might be in flower at that point. POM ensures both efficient pollination and fruit harvests in the future.",
      "Y",
      "N",
      "bee, beehive, multi-species, pollinator, flower, animals",
      "fabrication",
      "",
      "prototype"
    ],
    [
      "Mycotopia",
      "UK",
      "NAOMI ASHWORTH, BIANCA RUSSO, CAROLYN TAM, LARASATI GUNYUU, & THOMAS JAMES",
      "2017",
      "https://www.biodesignchallenge.org/royal-college-of-art",
      "Inspired by the interconnected networks of fungi in soil and plant interaction within these networks, Mycotopia is a mycelial planter system designed to recreate these networks within urban and domestic settings.",
      "Y",
      "N",
      "fungi, micro-organisms, planter, multi-species, symbiosis, utilization, material, rewild, mycellium",
      "fabrication, biomedia",
      "",
      "prototype"
    ],
    [
      "RootKnit",
      "Colombia",
      "PAULA ANDREA MOLINA OSORIO, NICOLE SENZ GIUSTI, & DANIEL SHAMBO RODRIGUEZ",
      "2017",
      "https://www.biodesignchallenge.org/universidad-de-los-andes",
      "RootKnit is a shapeshifting surface connected to plants. Using multiple sensors, RootKnit can react to the plants’ conditions and then translate that data into surface movements and shapes. This creates a new way of communicating, understanding, and connecting to plants and the environment.",
      "N",
      "N",
      "plants, biorhythm",
      "sensors, data",
      "transformation, fabric",
      "prototype"
    ],
    [
      "RXN Wristband",
      "USA",
      "JENNY FILIPETTI, ANDREW HENDERSON, STEPHEN LEWIS, & ALEX SWANSON",
      "2017",
      "https://www.ember.bio/#coming-soon",
      "RXN Wristband glows when a user’s blood alcohol content is over the legal limit to drive. It can be grown sustainably and biomanufactured at scale. Designers utilize the wearable as a platform for building and adding biosensors for new metrics.",
      "N",
      "N",
      "alcohol, utilization, material, synthetic biology",
      "sensors, biomedia, fabrication",
      "",
      "prototype"
    ],
    [
      "UK 2029: Post-Natural Artefacts from the United Kingdom of England and Wales",
      "Edinbrugh, UK",
      "EVA AUER, SEAN GREAVES, & JOSEPH REVANS",
      "2017",
      "https://biodesign.eca.ed.ac.uk/ukew-2029/\nhttps://cargocollective.com/UK2029/Wildflower-Protest",
      "UKEW 2029 explores how the socio-political landscape of the United Kingdom could interact with advances in biotechnology. A collection of physical artifacts, photographs, and text bring to life a possible future in which biotech is ubiquitous.\nThe project is presented as three fictional case studies which explore how communities existing today could navigate this future and utilise biotechnologies unique capabilities to pursue their goals. (Security and Protection – Dispersed Maker Communities; Biohacked Buildings – London; Wildflower Protests – Sheffield)",
      "Y",
      "Y",
      "multi-species, fungi, micro-organisms, synthetic biology, plants, utilization, resource, flower",
      "biomedia, fabrication, biotech",
      "community, political agenda, photography",
      "speculative"
    ],
    [
      "Cybele",
      "Edinbrugh, UK",
      "MAIA LYALL, CIRCLE LU, MUHAMAD IQBAL, & PANAYIOTIS PAVLIDES",
      "2017",
      "https://biodesign.eca.ed.ac.uk/cybele-an-artificial-asexual-womb/\nhttp://cybelebdc.wordpress.com",
      "Cybele, an interchangeable asexual incubator, envisions an artificial womb as a new mode of reproduction where families take equal part in growing a fetus. With Cybele, parents are able to create and incubate their children on shift without sexual interaction or restrictions of gender. Learn more about ",
      "N",
      "N",
      "regenerate, symbiosis",
      "fabrication, biotech",
      "parenthood",
      "speculative"
    ],
    [
      "Microbial Architecture",
      "Edinbrugh, UK",
      "RUOBING HAO & XINWEI DU",
      "2017",
      "https://biodesign.eca.ed.ac.uk/nature-authority-bio-architecture-designed-by-microorganisms/",
      "Microbial Architecture imagines what a building would look like from the eyes of microorganisms. It envisioning a world where the real authority comes from nature, which challenges the value of human-centric dominance.",
      "N",
      "N",
      "micro-organisms, ecology, more-than-human, environment, landscape",
      "fabrication, biomedia",
      "architecture, de-human-centric",
      "prototype"
    ],
    [
      "Fairyland: sensory bio-ecosystem for air pollution",
      "Edinbrugh, UK",
      "CORENTIN MOLLIER, SHAN LU, SHANNEN TIONIWAR, ZAZHONG WANG",
      "2017",
      "https://biodesign.eca.ed.ac.uk/pollutants-sensory-bio-ecosystem/",
      "an ecosystem that detects air pollution and enhances childrens' relationship to nature",
      "Y",
      "N",
      "multi-species, ecosystem, air, pollution, animals, insect, algae, plants",
      "fabrication, biomedia",
      "children",
      "prototype"
    ],
    [
      "Sharebiota– Interspecies Communication through Microbiota",
      "Edinbrugh, UK",
      "ALEJANDRA GRANDON, KIRSTY MILLAR, & YUXI LIU",
      "2017",
      "https://biodesign.eca.ed.ac.uk/sharebiota-interspecies-communication-through-microbiota/",
      "Sharebiota expands on recent discoveries that humans and their pets share beneficial strains of bacteria leading to healthier immune systems. It is a public installation that integrates collection, production, and distribution of dog microbiota.",
      "N",
      "N",
      "micro-organisms, dog, symbiosis, utilization, resource, animals, bacteria",
      "fabrication, sensors, biomedia, biotech",
      "",
      "speculative"
    ],
    [
      "Olfact-Sensory Communication Through Olfactory Genius",
      "Edinbrugh, UK",
      "KAREN CAMPA, KATIE DOBBERSTEIN, FABIEN FLOREK, & CORINNA HARTINGER",
      "2017",
      "https://biodesign.eca.ed.ac.uk/olfact-sensory-communication-through-olfactory-genius/",
      "Olfact encapsulates genetically engineered bacteria in a piece of jewelry to allow the wearer to capture a scent photograph/moment in time.",
      "N",
      "N",
      "bacteria, micro-organisms, material, utilization, more-than-human, smell",
      "biotech",
      "jewlery, smell/olfactory information, social relationship",
      "prototype"
    ],
    [
      "Fabiont",
      "NewYork, USA",
      "POOJA PATEL, YOUBIN LEE, PRATIK JAIN",
      "2018",
      "https://fabiont.carrd.co",
      "Fabiont aims to create a probiotic fabric to enhance the skin microbiome and reestablish the beneficial microbes it contains. The fabric incorporates probiotics in silk fibroins extracted from raw silk. The garment acts as an additional “skin” layer that augments the naturally given skin microbiome, a paradigm shift in both the fashion and skincare industries.",
      "N",
      "N",
      "micro-organisms, symbiosis, utilization, material, bacteria, skin",
      "biotech, biomedia",
      "",
      "prototype"
    ],
    [
      "Beyond 100%",
      "USA",
      "TUNG LIN, JAE KYONG CHEONG, SIHO CHANG",
      "2018",
      "https://www.biodesignchallenge.org/parsons-2018",
      "Beyond 100% imagines a microchip that can genetically modify a human’s capacity to acquire, manage, and share nutrition. The chip endows the user with the ability to receive nutrition from new food sources.",
      "N",
      "N",
      "food, multi-species, synthetic biology, animals",
      "biomedia, biotech",
      "",
      "speculative"
    ],
    [
      "Sorbit Diaper",
      "USA",
      "SERGIO GONZALEZ, JOLEE NIEBERDING-SWANBERG, ANNIE WANG, JULIE XU",
      "2018",
      "https://juliexu.wixsite.com/portfolio/sorbit\nhttps://www.biodesignchallenge.org/uc-davis",
      "Disposable diaper waste contributes to 3.4 million tons of landfill waste annually and are typically made of fossil-fuel derived plastics. Sorbit is a fully biodegradable diaper made out of bacterial cellulose grown from citrus agricultural waste. The material is soft, water-repellant on the outside, and absorbent on the inside.",
      "N",
      "N",
      "degrading, waste, material",
      "biomedia",
      "diaper",
      "prototype"
    ],
    [
      "Pressure Dependent Bioluminescence",
      "Edinburgh, UK",
      "WANYING ZHANG, YI HE, ROBIN BISHOP, GEDIZ ELIF KOCAOGLAN",
      "2018",
      "https://biodesign.eca.ed.ac.uk/pressure-dependent-bioluminescence/",
      "This project focused on the idea of using bioluminescence in a number of different settings. By designing a cutting-edge biologically advanced cell-free system, we are able to make use of pressure activated bioluminescence. We make use of the ‘PURE’ cell-free assembly kit to manufacture the constituent parts of the luminescent system. The system has a variety of different applications and uses in our day-to-day lives. ",
      "N",
      "N",
      "material, bioluminescence",
      "biomedia, biotech, fabrication",
      "children",
      "prototype"
    ],
    [
      "Nurture",
      "Edinburgh, UK",
      "MARK WILLIAMS, TARA WIGHT, YINGRUI MA, SAFA AJJAN",
      "2018",
      "https://biodesign.eca.ed.ac.uk/edible-architecture-growing-meals-at-home/",
      "The state of global food production is changing rapidly. The Nurture team is attempting to envision how the state of our food may look in 10 – 20 years time and discovering the problems we may face.\n\nNurture takes a new approach to eating and food preparation. Currently we are building a modular unit to contain our hydroponic and Spirulina growth systems, and we are also creating recipes for how people would be able to cook with this new ingredient, which we are putting in a cook book.",
      "Y",
      "N",
      "food, algae, utilization, resource",
      "biomedia, biotech, fabrication",
      "home-grow, agriculture",
      "speculative"
    ]
  ]
}
